function du=SplineBasisDerivative(x, k)
  t = ( x - k + 1 );

du=zeros(size(x))+ ...
(-3*(2-t).*(2-t)).*((t <= 2) & (t >= 1))+ ...
  (-12*t+9*t.^2).*((t < 1) & (t >= 0))+ ...
  (-12*t-9*t.^2).*((t < 0) & (t >= -1))+ ...
  (3*(2+t).*(2+t)).*((t < -1) & (t >= -2));
           
 
